# wrangler.toml — for Cloudflare Pages only

name                    = "bolt-diy"
account_id              = "b5d1065d53509de0f67f356ac80de9a9"
compatibility_date      = "2025-04-24"
type                    = "javascript"

# ← Pages needs this:
pages_build_output_dir  = "build"
