name = "bolt-diy"
compatibility_date = "2025-04-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[build]
  command = "npm ci && npm run build"
  upload_format = "modules"

[functions]
  directory = "functions"
